version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: avanti-mongodb
    restart: always
    ports:
      - "${DATABASE_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - avanti-network

volumes:
  mongodb_data:

networks:
  avanti-network:
    driver: bridge 